### ISSUE TITLE
nvi-gtk hangs if any error in config file or file has lock

### ISSUE THREAD

**Issue by oroulet** [Lyude/neovim-gtk#28]
**Describe the bug**
nvim-gtk -- myfile.rs  # fine it opens
nvim-gk -- myfile.rs #hangs indefinitely
nvim myfile.rs  # displat the expected error mesage that file is already opened

This is so obvious I am expecting this is a well known bug but I cannot find it so here is a bug report
 
![image](https://user-images.githubusercontent.com/2564046/164909113-5ee7f435-5fda-403b-99e4-7548708c22ab.png)

![image](https://user-images.githubusercontent.com/2564046/164909125-4725c09a-471f-4092-8804-cad86a76eb49.png)

![image](https://user-images.githubusercontent.com/2564046/164909158-27574db6-761a-4dde-ba21-e113410c7f28.png)

**Technical information (please complete the following information):**
 - OS: ubuntu
 - Neovim version: nightly
 - Neovim-Gtk build version: github master

**Comment by oroulet** [comment]
found a similar one in original repository: https://github.com/daa84/neovim-gtk/issues/239

**Comment by Lyude** [comment]
Actually, going to close this - I don't think this is a bug. launching things via `nvim-gtk --` isn't supported because that passes the filename directly to nvim - which means we don't have control over when the files are opened. As a result, we also don't know when we're in an error prompt or not and as such - end up blocking on calls we expect to finish that never will because of said prompt.

The solution for this is to just open the file like so: `nvim-gtk foo`. If that doesn't work for some reason, e.g. there's some neovim option you want that isn't supported by `nvim-gtk` yet then I'd suggest opening up a separate issue asking for it. Usually porting additional CLI flags isn't too much work :)

**Comment by Lyude** [comment]
I did realize though that there's technically two unrelated issues here: the hang from commandline arguments, and errors resulting from an invalid `.vimrc` on start. The second problem actually may be fixabl, so I'm going to open a separate issue for it
