### ISSUE TITLE
Resizing to a smaller window works in macOS, but not to a window larger than the default size

### ISSUE THREAD

**Issue by jacobmischka** [Lyude/neovim-gtk#46]
Pretty much the title. The fact that it only happens when upsizing and not downsizing makes me think it's a bug in this project and not GTK's macOS implementation itself. I'm looking into this myself as it obviously doesn't reproduce on Linux, but if you have any ideas of where to look that would help a lot!

https://user-images.githubusercontent.com/3939997/208730989-9bdb3d38-52b4-498b-86cc-112cc1409e47.mp4

**Technical information (please complete the following information):**
 - OS: macOS
 - Neovim version: 0.8.1
 - Neovim-Gtk build version: a3b9af7f8b63129336448ab850ef1984fd1ad35f

**Comment by Lyude** [comment]
This looks like a gtk4 bug on OSX possibly? I can't think of any other reason why doing something like changing the background styling would do break something like this. Have you tried the gtk inspector (I added `call rpcnotify(1, 'Gui', 'Command', 'ShowGtkInspector')` a while ago for this) to see if setting the background class there instead of in style.css makes any difference?

**Comment by jacobmischka** [comment]
Yes, that's how I found that the CSS class fixed it by using the inspector.
