### ISSUE TITLE
Put current filename at the beginning of the window title and path in parenthesis

### ISSUE THREAD

**Issue by sdroege** [Lyude/neovim-gtk#55]
This would be the same behaviour as gvim, and makes it easier to spot which file is actually open in the window. In addition, normalizing the home directory to `~` would also save a bit of space.

gvim also includes an indicator (`+`) in the title if the file was modified, and the number of files in the current buffer, which is also both useful to have.

![image](https://user-images.githubusercontent.com/301846/209443765-feda0115-d726-4a6b-8752-1f7c58ba3ad4.png)

**Comment by Lyude** [comment]
JFYI: I think this is a pretty good idea, I've been wanting to add some more info to the titlebar (and GUI tabs at some point as well…) for a while now. The behavior I have in mind after looking at this is only slightly different. Basically:

* Use different title styles depending on whether or not we have a header bar. For the header bar, I'd do something like this:
  * _(with a header bar)_
     gstavvidenc.c + (1 of 2) - nvim-gtk
     ~/Projects/gstreamer/gstreamer/subprojects/gst-libav/ext/libav
  * _(without a header bar)_
     gstavvidenc.c + (~/Projects/gstreamer/gstreamer/subprojects/gst-libav/ext/libav) (1 of 2) - nvim-gtk
* But, use the header-bar-less style for the actual `ApplicationWindow` window title, so that we see that title in the DE
