### ISSUE TITLE
Add missing platforms to CI

### ISSUE THREAD

**Issue by Lyude** [Lyude/neovim-gtk#72]
Currently we're still missing coverage in our CI for the following two platforms:

- [x] Windows
  Should be pretty easy, there's instructions for building the GTK3 version of neovim [in the appveyor.yml that we removed](https://github.com/Lyude/neovim-gtk/blob/f8f0ad38f7fd1c8f6d9908effb660f13a0afd50c/appveyor.yml)
- [x] OSX (@jacobmischka, how do you typically build this? I probably could give a shot at at)

**Comment by jacobmischka** [comment]
I've only done it from scratch once, but I think I just installed gtk and other system libraries using homebrew and then ran cargo install. I vaguely remember one small hiccup but I don't think it was anything major.

Honestly not sure how to start this over myself because of how weird homebrew is, but happy to mess with CI until it works!

**Comment by Lyude** [comment]
> I've only done it from scratch once, but I think I just installed gtk and other system libraries using homebrew and then ran cargo install. I vaguely remember one small hiccup but I don't think it was anything major.
> 
> Honestly not sure how to start this over myself because of how weird homebrew is, but happy to mess with CI until it works!

I actually ended up messing a bit with CI today and ended up getting it working :), turns out it's surprisingly easy (after fighting a bit with brew)
